name: Run Python Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
#   schedule:
    # Run once a day at midnight UTC (optional)
    # - cron: '0 0 * * *'
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  run-script:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Specify the Python version you need

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: '.github/workflows/main.yml'

      - name: Install dependencies
        run: |
          uv pip install --system seleniumbase curl-cffi

      - name: Install xvfb (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Run script (Linux)
        if: runner.os == 'Linux'
        run: xvfb-run python script-fazenda.py

      - name: Run script (Windows)
        if: runner.os == 'Windows'
        run: python script-fazenda.py
